from __future__ import annotations

MODELS = [
    {
        "id": "diffusion",
        "name": "Diffusion Model",
        "tagline": "Generative Reconstruction",
        "type": "Diffusion",
        "description": "Open, local diffusion-inspired reconstruction pipeline with iterative denoising and context fusion.",
        "speed": "Slow",
        "params": "120M",
        "color": "#ec4899",
        "quality": {"ssim": 0.951, "psnr": 29.18, "sam": 3.6, "fidelity": 99.1},
        "backend": "Local denoising + multi-pass inpainting",
    },
    {
        "id": "swin-transformer",
        "name": "Swin-Transformer",
        "tagline": "High Fidelity",
        "type": "Transformer",
        "description": "Hierarchical attention-guided reconstruction tuned for edge preservation and spatial detail.",
        "speed": "Moderate",
        "params": "88M",
        "color": "#10b981",
        "quality": {"ssim": 0.942, "psnr": 28.45, "sam": 4.2, "fidelity": 98.2},
        "backend": "Edge-preserving inpainting + sharpened context blending",
    },
    {
        "id": "hybrid-cgan",
        "name": "Hybrid cGAN",
        "tagline": "Fast Spatial Mapping",
        "type": "GAN",
        "description": "Fast conditional reconstruction that uses optical context and SAR guidance to restore clouds.",
        "speed": "Fast",
        "params": "42M",
        "color": "#14b8a6",
        "quality": {"ssim": 0.918, "psnr": 26.82, "sam": 5.1, "fidelity": 96.4},
        "backend": "Morphology-aware inpainting + SAR detail injection",
    },
    {
        "id": "pix2pix",
        "name": "Pix2Pix Generator",
        "tagline": "Paired Translation",
        "type": "GAN",
        "description": "Paired-image translation baseline with moderate smoothing and structure restoration.",
        "speed": "Fast",
        "params": "54M",
        "color": "#06b6d4",
        "quality": {"ssim": 0.901, "psnr": 25.67, "sam": 5.8, "fidelity": 94.8},
        "backend": "Telea fill + local contrast normalization",
    },
    {
        "id": "cyclegan",
        "name": "CycleGAN",
        "tagline": "Unpaired Feature Translation",
        "type": "GAN",
        "description": "Unpaired translation pipeline for scenes where clean reference pairs are limited or unavailable.",
        "speed": "Moderate",
        "params": "48M",
        "color": "#8b5cf6",
        "quality": {"ssim": 0.887, "psnr": 24.91, "sam": 6.4, "fidelity": 93.1},
        "backend": "Histogram matching + smooth style transfer",
    },
    {
        "id": "unet-attention",
        "name": "U-Net + Attention",
        "tagline": "Baseline",
        "type": "CNN",
        "description": "Attention-gated U-Net style baseline with strong local context and conservative reconstruction.",
        "speed": "Very Fast",
        "params": "31M",
        "color": "#f59e0b",
        "quality": {"ssim": 0.876, "psnr": 24.12, "sam": 6.9, "fidelity": 91.5},
        "backend": "Expanded cloud mask + median fusion",
    },
]

DATASETS = [
    {"name": "LISS-IV Optical", "source": "Bhoonidhi / ISRO", "role": "Primary", "resolution": "5.8m", "bands": "4 (VNIR)"},
    {"name": "Sentinel-1 SAR", "source": "Copernicus", "role": "Auxiliary", "resolution": "10m", "bands": "VV/VH"},
    {"name": "Sentinel-2 MSI", "source": "Copernicus", "role": "Auxiliary", "resolution": "10m", "bands": "13 bands"},
    {"name": "Temporal Reference", "source": "Bhoonidhi Archive", "role": "Auxiliary", "resolution": "5.8m", "bands": "Multi-date"},
    {"name": "SRTM DEM", "source": "USGS/NASA", "role": "Auxiliary", "resolution": "30m", "bands": "Elevation"},
]

PREPROCESSING_STEPS = [
    {
        "id": 1,
        "title": "Data Acquisition",
        "description": "Collect cloudy and cloud-free LISS-IV scenes from Bhoonidhi portal for NER study areas.",
        "tools": ["Bhoonidhi", "ISRO LISS-IV"],
        "status": "complete",
    },
    {
        "id": 2,
        "title": "Radiometric Correction",
        "description": "Apply DN to TOA reflectance conversion and atmospheric correction for spectral consistency.",
        "tools": ["GDAL", "Rasterio"],
        "status": "complete",
    },
    {
        "id": 3,
        "title": "Cloud Mask Generation",
        "description": "Generate cloud and cloud-shadow masks using a local segmentation heuristic and QA refinement.",
        "tools": ["OpenCV", "NumPy"],
        "status": "active",
    },
    {
        "id": 4,
        "title": "Auxiliary Co-registration",
        "description": "Align Sentinel-1 SAR, Sentinel-2 optical, DEM, and temporal reference imagery to LISS-IV grid.",
        "tools": ["GDAL", "Rasterio", "QGIS"],
        "status": "pending",
    },
    {
        "id": 5,
        "title": "Patch Extraction",
        "description": "Extract 256x256 overlapping patches with augmentation for model training and validation.",
        "tools": ["Albumentations", "NumPy"],
        "status": "pending",
    },
    {
        "id": 6,
        "title": "Quality Control",
        "description": "Validate co-registration RMSE, mask coverage ratios, and spectral histogram alignment.",
        "tools": ["NumPy", "QGIS"],
        "status": "pending",
    },
]

WORKFLOW_STEPS = [
    {
        "phase": "Ingestion",
        "steps": ["Upload LISS-IV cloudy scene", "Attach optional SAR/S2/DEM layers", "Auto-generate cloud mask"],
    },
    {
        "phase": "Processing",
        "steps": ["Co-register auxiliary data", "Select GenAI architecture", "Run inference pipeline"],
    },
    {
        "phase": "Validation",
        "steps": ["Compute SSIM, PSNR, SAM metrics", "Visual before/after comparison", "Export analysis-ready GeoTIFF"],
    },
    {
        "phase": "Deployment",
        "steps": ["Batch processing queue", "API endpoint integration", "Operational monitoring dashboard"],
    },
]

EVALUATION_SAMPLES = [
    {"region": "Assam — Brahmaputra Floodplain", "cloudCover": "34%", "improvement": "High"},
    {"region": "Meghalaya — Khasi Hills", "cloudCover": "52%", "improvement": "Very High"},
    {"region": "Arunachal — Himalayan Foothills", "cloudCover": "41%", "improvement": "High"},
    {"region": "Nagaland — Forest Canopy", "cloudCover": "28%", "improvement": "Moderate"},
]

TECH_STACK = [
    {"category": "Deep Learning", "items": ["PyTorch", "torchvision", "NumPy"]},
    {"category": "Geospatial", "items": ["GDAL", "Rasterio", "QGIS"]},
    {"category": "Processing", "items": ["OpenCV", "NumPy", "Scikit-image"]},
    {"category": "Deployment", "items": ["FastAPI", "Next.js", "Vercel", "Docker"]},
]

MODEL_PROFILES = {
    "diffusion": {
        "mask_dilation": 3,
        "inpaint_radius": 7,
        "bilateral_d": 11,
        "bilateral_sigma_color": 60,
        "bilateral_sigma_space": 55,
        "blend": 0.56,
        "gamma": 1.02,
        "detail_strength": 0.24,
        "quality_bonus": 0.08,
        "stage_steps": 5,
    },
    "swin-transformer": {
        "mask_dilation": 2,
        "inpaint_radius": 5,
        "bilateral_d": 9,
        "bilateral_sigma_color": 48,
        "bilateral_sigma_space": 42,
        "blend": 0.64,
        "gamma": 1.0,
        "detail_strength": 0.18,
        "quality_bonus": 0.06,
        "stage_steps": 4,
    },
    "hybrid-cgan": {
        "mask_dilation": 2,
        "inpaint_radius": 4,
        "bilateral_d": 7,
        "bilateral_sigma_color": 36,
        "bilateral_sigma_space": 30,
        "blend": 0.7,
        "gamma": 1.0,
        "detail_strength": 0.14,
        "quality_bonus": 0.04,
        "stage_steps": 3,
    },
    "pix2pix": {
        "mask_dilation": 1,
        "inpaint_radius": 4,
        "bilateral_d": 7,
        "bilateral_sigma_color": 32,
        "bilateral_sigma_space": 26,
        "blend": 0.72,
        "gamma": 1.0,
        "detail_strength": 0.1,
        "quality_bonus": 0.03,
        "stage_steps": 3,
    },
    "cyclegan": {
        "mask_dilation": 2,
        "inpaint_radius": 5,
        "bilateral_d": 9,
        "bilateral_sigma_color": 42,
        "bilateral_sigma_space": 36,
        "blend": 0.74,
        "gamma": 1.03,
        "detail_strength": 0.08,
        "quality_bonus": 0.02,
        "stage_steps": 4,
    },
    "unet-attention": {
        "mask_dilation": 4,
        "inpaint_radius": 6,
        "bilateral_d": 9,
        "bilateral_sigma_color": 52,
        "bilateral_sigma_space": 44,
        "blend": 0.78,
        "gamma": 1.0,
        "detail_strength": 0.11,
        "quality_bonus": 0.01,
        "stage_steps": 4,
    },
}